DELETE FROM ONLINE_PRODUCT;
DELETE FROM ONLINE_CATEGORY;

INSERT INTO ec.`ONLINE_CATEGORY`(`CTGR_ID`,`NAME`,`LAST_UPD_DATE`) VALUES (0,'サプリ',NULL);
INSERT INTO ec.`ONLINE_CATEGORY`(`CTGR_ID`,`NAME`,`LAST_UPD_DATE`) VALUES (1,'シューズ',NULL);
INSERT INTO ec.`ONLINE_CATEGORY`(`CTGR_ID`,`NAME`,`LAST_UPD_DATE`) VALUES (2,'アクセサリ',NULL);


INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000001',0,'サプリA','A社',100,'2020/06/01',1111,'01.jpeg','サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。','0','2020/06/01 9:06:39');
INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000002',0,'シューズA','A社',10,'2020/06/01',5000,'13.jpeg','シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。','0','2020/06/01 9:32:17');
INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000003',0,'アクセサリA','A社',5,'2020/06/02',3000,'25.jpeg','アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。','0',NULL);
INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000004',1,'サプリA','A社',100,'2020/06/01',1111,'01.jpeg','サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。サプリAです。','0','2020/06/01 9:06:39');
INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000005',1,'シューズA','A社',10,'2020/06/01',5000,'13.jpeg','シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。シューズAです。','0','2020/06/01 9:32:17');
INSERT INTO ec.`ONLINE_PRODUCT`(`PRODUCT_CODE`,`CATEGORY_ID`,`PRODUCT_NAME`,`MAKER`,`STOCK_COUNT`,`REGISTER_DATE`,`UNIT_PRICE`,`PICTURE_NAME`,`MEMO`,`DELETE_FLG`,`LAST_UPD_DATE`) VALUES ('00000000000006',1,'アクセサリA','A社',5,'2020/06/02',3000,'25.jpeg','アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。アクセサリAです。','0',NULL);
